default_platform(:ios)

platform :ios do
  desc "Build and upload to TestFlight"
  lane :beta do
    sh "cd ../.. && flutter build ipa --release --dart-define-from-file=env/prod.json --export-options-plist=ios/ExportOptions.plist"
    upload_to_testflight(
      ipa: '../build/ios/ipa/qnote.ipa',
      skip_waiting_for_build_processing: true
    )
  end

  desc "Deploy to App Store"
  lane :release do
    sh "cd ../.. && flutter build ipa --release --dart-define-from-file=env/prod.json --export-options-plist=ios/ExportOptions.plist"
    upload_to_app_store(
      ipa: '../build/ios/ipa/qnote.ipa',
      skip_metadata: false,
      skip_screenshots: true,
      force: true
    )
  end
end
