default_platform(:android)

platform :android do
  desc "Build and deploy to Google Play internal testing"
  lane :internal do
    sh "cd ../.. && flutter build appbundle --release"
    upload_to_play_store(
      track: 'internal',
      aab: '../build/app/outputs/bundle/release/app-release.aab',
      skip_upload_metadata: true,
      skip_upload_changelogs: true,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end

  desc "Build release APK"
  lane :build do
    sh "cd ../.. && flutter build apk --release"
  end

  desc "Deploy to production"
  lane :production do
    sh "cd ../.. && flutter build appbundle --release"
    upload_to_play_store(
      track: 'production',
      aab: '../build/app/outputs/bundle/release/app-release.aab'
    )
  end
end
